# fly.toml app configuration file generated for ruby-3-3-0-fly-crash on 2024-01-14T07:53:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ruby-3-3-0-fly-crash"
primary_region = "bog"
# swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
